"""add co2

Revision ID: 426aae1ceca4
Revises: 
Create Date: 2024-09-16 00:10:27.613655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426aae1ceca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('co2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'co2')
    # ### end Alembic commands ###
